<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0-windows</TargetFramework></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Smart.Hosting/Smart.Hosting.csproj" />
    <ProjectReference Include="../Smart.Adapters.Dma/Smart.Adapters.Dma.csproj" />
    <ProjectReference Include="../Smart.Adapters.KmBox/Smart.Adapters.KmBox.csproj" />
  </ItemGroup>
</Project>
