<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationIcon>Source\Picture\Logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="vmmsharp">
      <HintPath>Lib\vmmsharp.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Native\MemProcFS\*.dll" Link="%(Filename)%(Extension)" Condition="Exists('Native\MemProcFS\vmm.dll')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Source\client_skills.xml" Condition="Exists('Source\client_skills.xml')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
