<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Roadhog\Roadhog.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="vmmsharp">
      <HintPath>..\Roadhog\Lib\vmmsharp.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
