local cwd = sys and sys.get_cwd and sys.get_cwd() or "."
package.path = cwd .. "/scripts/?.lua;" .. cwd .. "/scripts/?/init.lua;" .. package.path

local Probe = require("maple.probes.api_probe")

return Probe.platform_combat({
    account_index = tonumber(account_index) or 0,
    target_name = probe_target_name or "msw.exe",
    license_key = probe_license_key,
    platform_path = probe_platform_path,
    run_seconds = tonumber(probe_run_seconds) or 0,
    max_ticks = tonumber(probe_max_ticks) or 0,
    clear_remaining_threshold = tonumber(probe_clear_remaining_threshold) or 0,
    pickup_empty_confirm_ticks = tonumber(probe_pickup_empty_confirm_ticks) or 5,
    key_name = probe_key_name or "Shift",
    key_code = tonumber(probe_key_code) or 0x10,
    input_mode = probe_input_mode or "foreground",
    key_mode = probe_key_mode,
    hold_ms = tonumber(probe_hold_ms) or 0,
    skill_range_x = tonumber(probe_skill_range_x) or 2.0,
    skill_range_y = tonumber(probe_skill_range_y) or 0.3,
    preferred_attack_distance = tonumber(probe_preferred_attack_distance) or 1.4,
    cast_delay_seconds = tonumber(probe_cast_delay_seconds) or 0.7,
    actor_platform_y_tolerance = tonumber(probe_actor_platform_y_tolerance) or 0.6,
    platform_y_tolerance = tonumber(probe_platform_y_tolerance) or 1.0,
    pickup_platform_y_tolerance = tonumber(probe_pickup_platform_y_tolerance) or 1.5,
    grounded_y_tolerance = tonumber(probe_grounded_y_tolerance) or 0.2,
    platform_x_margin = tonumber(probe_platform_x_margin) or 0.2,
    platform_safe_margin = tonumber(probe_platform_safe_margin) or 0.5,
    arrival_tolerance_x = tonumber(probe_arrival_tolerance_x) or 0.18,
    move_ms = tonumber(probe_move_ms) or 180,
    pickup_move_ms = tonumber(probe_pickup_move_ms) or 360,
    pickup_move_method = probe_pickup_move_method or "key",
    move_method = probe_move_method or "key",
    move_left_key_code = tonumber(probe_move_left_key_code) or 0x25,
    move_right_key_code = tonumber(probe_move_right_key_code) or 0x27,
    face_ms = tonumber(probe_face_ms) or 80,
    face_method = probe_face_method or "key",
    face_left_key_code = tonumber(probe_face_left_key_code) or 0x25,
    face_right_key_code = tonumber(probe_face_right_key_code) or 0x27,
    attack_wait_ms = tonumber(probe_attack_wait_ms) or 750,
    pick_wait_ms = tonumber(probe_pick_wait_ms) or 250,
    pickup_pick_repeat = tonumber(probe_pickup_pick_repeat) or 1,
    pickup_pick_repeat_ms = tonumber(probe_pickup_pick_repeat_ms) or 100,
    pickup_drop_fail_threshold = tonumber(probe_pickup_drop_fail_threshold) or 1,
    pickup_drop_ignore_ticks = tonumber(probe_pickup_drop_ignore_ticks) or 60,
    pickup_drop_ignore_cluster_x = tonumber(probe_pickup_drop_ignore_cluster_x) or 0.75,
    pickup_drop_ignore_cluster_y = tonumber(probe_pickup_drop_ignore_cluster_y) or 1.0,
    pickup_key_enabled = probe_pickup_key_enabled ~= false,
    pickup_key_name = probe_pickup_key_name or "Z",
    pickup_key_code = tonumber(probe_pickup_key_code) or 0x5A,
    pickup_key_repeat = tonumber(probe_pickup_key_repeat) or 3,
    pickup_key_repeat_ms = tonumber(probe_pickup_key_repeat_ms) or 80,
    pickup_key_hold_ms = tonumber(probe_pickup_key_hold_ms) or 80,
    tick_ms = tonumber(probe_tick_ms) or 120,
    pickup_range_x = tonumber(probe_pickup_range_x) or 0.65,
    pickup_range_y = tonumber(probe_pickup_range_y) or 0.5,
    pickup_ignore_raw_y = probe_pickup_ignore_raw_y ~= false,
    pickup_enabled = probe_pickup_enabled ~= false,
    pickup_during_combat_enabled = probe_pickup_during_combat_enabled ~= false,
    pickup_during_combat_nearby_range_x = tonumber(probe_pickup_during_combat_nearby_range_x) or 0.8,
    pickup_during_combat_max_detour_x = tonumber(probe_pickup_during_combat_max_detour_x) or 1.5,
    pickup_age_priority_ticks = tonumber(probe_pickup_age_priority_ticks) or 80,
    pickup_include_all_drops = probe_pickup_include_all_drops ~= false,
    pickup_sweep_enabled = probe_pickup_sweep_enabled == true,
    pickup_sweep_step = tonumber(probe_pickup_sweep_step) or 0.35,
    pickup_sweep_arrival_x = tonumber(probe_pickup_sweep_arrival_x) or 0.15,
    pickup_sweep_safe_margin = tonumber(probe_pickup_sweep_safe_margin) or 0.1,
    pickup_sweep_max_ticks = tonumber(probe_pickup_sweep_max_ticks) or 600,
    fallback_to_basic_attack = probe_fallback_to_basic_attack ~= false
})
